// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_vRKWhzbIPcx8vTmaYHzzGTof5YmfO7c',
    appId: '1:908932636138:web:4d2e5b03a7866ebae1e693',
    messagingSenderId: '908932636138',
    projectId: 'flutter-ai-dev-2430f',
    authDomain: 'flutter-ai-dev-2430f.firebaseapp.com',
    storageBucket: 'flutter-ai-dev-2430f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbe9N-biN9f-V1eyNhQhSQdIilNDKQUT4',
    appId: '1:908932636138:android:814294e58437a718e1e693',
    messagingSenderId: '908932636138',
    projectId: 'flutter-ai-dev-2430f',
    storageBucket: 'flutter-ai-dev-2430f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCs71OztZlgLgDJk3QuHd9ZHdIKieNb3s',
    appId: '1:908932636138:ios:640e560424832555e1e693',
    messagingSenderId: '908932636138',
    projectId: 'flutter-ai-dev-2430f',
    storageBucket: 'flutter-ai-dev-2430f.firebasestorage.app',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCs71OztZlgLgDJk3QuHd9ZHdIKieNb3s',
    appId: '1:908932636138:ios:640e560424832555e1e693',
    messagingSenderId: '908932636138',
    projectId: 'flutter-ai-dev-2430f',
    storageBucket: 'flutter-ai-dev-2430f.firebasestorage.app',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_vRKWhzbIPcx8vTmaYHzzGTof5YmfO7c',
    appId: '1:908932636138:web:abe2e469a15c833de1e693',
    messagingSenderId: '908932636138',
    projectId: 'flutter-ai-dev-2430f',
    authDomain: 'flutter-ai-dev-2430f.firebaseapp.com',
    storageBucket: 'flutter-ai-dev-2430f.firebasestorage.app',
  );
}
